version: '3.1'
services:
  app:
    container_name: trainingmanager
    image: app-springboot-postgresql
    build: ./
    ports:
      - "8086:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=trainingmanager